# Generated by Django 4.2 on 2023-12-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_alter_blog_text_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='isactive',
            field=models.BooleanField(null=True, verbose_name='Sayfada Göster'),
        ),
        migrations.AddField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(blank=True, default='Alt Başlık Yoktur.', max_length=50, verbose_name='Alt Başlık'),
        ),
    ]
