# Generated by Django 4.2 on 2023-12-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0004_blog_isactive_blog_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='isactive',
            field=models.BooleanField(default=False, verbose_name='Sayfada Göster'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alt Başlık'),
        ),
    ]
